#!/usr/bin/env python3
"""Generate component metrics from @gravity-ui/uikit's compiled component CSS.

    npm pack @gravity-ui/uikit@7.49.0 && tar xzf gravity-ui-uikit-7.49.0.tgz
    python tools/gen-metrics/gen_metrics.py --package ./package
    python tools/gen-metrics/gen_metrics.py --package ./package --check   # CI

Writes src/Tokens/ComponentMetrics.qml. That file is generated -- edit this script,
not it.

Every component stylesheet in the package is written to the same protocol: the
block declares a set of local custom properties (`--_--height`, `--_--padding`,
`--_--border-radius`, ...) and each modifier overrides them:

    .g-button            { --_--focus-outline-offset: 0; }
    .g-button_size_m     { --_--height: 28px; --_--padding: 12px; }
    .g-button_size_l     { --_--height: 36px; --_--padding: 16px; }

That is a lookup table with a regular shape, so it is read rather than
transcribed: 62 components' worth of heights, paddings, gaps and radii would
otherwise be copied by eye, and every one of those copies is a chance to be
quietly wrong.

Only values that resolve to a length survive. Colours, shadows and keywords are
left out: those are not metrics, and components read them from Theme.colors.
Anything the generator cannot type -- a modifier with no matching enum, a
selector combining two modifiers -- is skipped and reported, so what is missing
is visible instead of silently absent.
"""

import argparse
import collections
import glob
import os
import re
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                "..", "gen-tokens"))
from gen_tokens import read_block, declarations, resolve  # noqa: E402

HEADER = ("// GENERATED by tools/gen-metrics/gen_metrics.py from "
          "@gravity-ui/uikit {version}. Do not edit by hand.\n")

# .g-button / .g-button_size_m / .g-segmented-radio-group_size_xl
SELECTOR = re.compile(r'^\.g-([a-z0-9]+(?:-[a-z0-9]+)*?)'
                      r'(?:_([a-z0-9]+(?:-[a-z0-9]+)*)_([a-z0-9-]+))?$')
RULE = re.compile(r'([^{}]+)\{([^{}]*)\}', re.S)
LOCAL = re.compile(r'--_--([a-z0-9-]+)\s*:\s*([^;]+);')
COMMENT = re.compile(r'/\*.*?\*/', re.S)

LENGTH = re.compile(r'^-?\d*\.?\d+px$')
NUMBER = re.compile(r'^-?\d*\.?\d+$')
SAFE_CALC = re.compile(r'^[\d\s.+\-*/()]+$')

# CSS modifier value -> Core enum member. A dimension is only emitted when
# every one of its values maps.
ENUMS = {
    "size": ("GSize", {
        "3xs": "Xxxs", "2xs": "Xxs", "xxs": "Xxs", "xs": "Xs",
        "s": "S", "m": "M", "l": "L", "xl": "Xl",
    }),
    "view": ("GView", {
        "normal": "Normal", "action": "Action", "raised": "Raised",
        "outlined": "Outlined", "flat": "Flat", "filled": "Filled",
        "clear": "Clear",
        "outlined-info": "OutlinedInfo", "outlined-success": "OutlinedSuccess",
        "outlined-warning": "OutlinedWarning", "outlined-danger": "OutlinedDanger",
        "outlined-utility": "OutlinedUtility", "outlined-action": "OutlinedAction",
        "flat-secondary": "FlatSecondary", "flat-info": "FlatInfo",
        "flat-success": "FlatSuccess", "flat-warning": "FlatWarning",
        "flat-danger": "FlatDanger", "flat-utility": "FlatUtility",
        "flat-action": "FlatAction", "normal-contrast": "NormalContrast",
        "outlined-contrast": "OutlinedContrast", "flat-contrast": "FlatContrast",
    }),
    "theme": ("GTheme", {
        "normal": "Normal", "info": "Info", "success": "Success",
        "warning": "Warning", "danger": "Danger", "utility": "Utility",
        "unknown": "Unknown", "clear": "Clear", "brand": "Brand",
        "misc": "Misc",
    }),
    "direction": ("GDirection", {"horizontal": "Horizontal", "vertical": "Vertical",
                                 "row": "Horizontal", "column": "Vertical"}),
    "orientation": ("GDirection", {"horizontal": "Horizontal", "vertical": "Vertical"}),
    "shape": ("GShape", {"circle": "Circle", "square": "Square"}),
}

# CSS shorthand order for the value counts worth splitting.
SHORTHAND = {
    2: ("Block", "Inline"),
    4: ("Top", "Right", "Bottom", "Left"),
}


def metric_name(block, variable):
    """Component + variable, minus the block name when the variable repeats it."""
    prefix = block + "-"
    if variable.startswith(prefix):
        variable = variable[len(prefix):]
    return camel(block) + camel(variable, upper=True)


def camel(kebab, upper=False):
    parts = [p for p in kebab.replace("_", "-").split("-") if p]
    head = parts[0].capitalize() if upper else parts[0]
    return head + "".join(p.capitalize() for p in parts[1:])


def root_variables(package):
    """The global custom properties every component resolves against."""
    path = os.path.join(package, "styles", "styles.css")
    with open(path, encoding="utf-8") as fh:
        css = fh.read()
    root = {}
    for m in re.finditer(r'\.g-root[^{}]*\{', css):
        root.update(declarations(read_block(css, m.end() - 1)))
    return root


def split_values(value):
    """Split a shorthand on top-level whitespace, keeping var()/calc() whole."""
    parts, depth, current = [], 0, ""
    for ch in value:
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
        if ch.isspace() and depth == 0:
            if current:
                parts.append(current)
                current = ""
            continue
        current += ch
    if current:
        parts.append(current)
    return parts


def as_length(value, root):
    """Return the value in px, or None if it is not a plain length."""
    value = resolve_inline(value, root)
    if value is None:
        return None
    value = value.strip()
    if LENGTH.match(value):
        return float(value[:-2])
    if NUMBER.match(value):
        return float(value)
    m = re.match(r'^calc\((.*)\)$', value, re.S)
    if m:
        expr = m.group(1).replace("px", "")
        if not SAFE_CALC.match(expr):
            return None
        try:
            return float(eval(expr, {"__builtins__": {}}, {}))  # arithmetic only
        except (SyntaxError, ZeroDivisionError, NameError, TypeError):
            return None
    return None


def resolve_inline(value, root):
    """Expand var() references against the root table."""
    for _ in range(16):
        m = re.search(r'var\(\s*(--[\w-]+)\s*(?:,\s*([^()]*))?\)', value)
        if not m:
            return value
        inner = resolve(m.group(1), {}, root)
        if inner is None:
            inner = (m.group(2) or "").strip()
            if not inner:
                return None
        value = value[:m.start()] + inner + value[m.end():]
    return None


def number(value):
    return str(int(value)) if float(value).is_integer() else repr(round(value, 4))


def collect(package):
    """{component: {metric: {"base": v, "dim": d, "cases": {enum: v}}}} + skips."""
    root = root_variables(package)
    pattern = os.path.join(package, "build", "esm", "components", "**", "*.css")
    table = collections.defaultdict(lambda: collections.defaultdict(dict))
    skipped = collections.Counter()

    for path in sorted(glob.glob(pattern, recursive=True)):
        # The plan does not port these, so their metrics are noise.
        if re.search(r'[\\/](lab|legacy|mobile)[\\/]', path):
            continue
        with open(path, encoding="utf-8") as fh:
            css = COMMENT.sub("", fh.read())
        for selector, body in RULE.findall(css):
            locals_ = LOCAL.findall(body)
            if not locals_:
                continue
            # A rule can list several selectors, and the text before the
            # first one still carries whatever preceded the block (@charset,
            # a previous rule's closing brace).
            selector = selector.split("}")[-1].split(";")[-1]
            targets = []
            for one in selector.split(","):
                one = one.strip()
                match = SELECTOR.match(one)
                if match:
                    targets.append(match.groups())
                else:
                    skipped["selector: %s" % one] += 1
            if not targets:
                continue

            for block, dimension, value_name in targets:
                emit_declarations(table, skipped, root, locals_,
                                  block, dimension, value_name)

    merge_shorthands(table)
    prune(table)
    return table, skipped


def emit_declarations(table, skipped, root, locals_, block, dimension, value_name):
            for raw_name, raw_value in locals_:
                for suffix, part in expand(raw_name, raw_value, root):
                    metric = table[camel(block)][
                        metric_name(block, raw_name)[len(camel(block)):] + suffix]
                    if dimension is None:
                        metric["base"] = part
                        continue
                    enum = ENUMS.get(dimension)
                    if enum is None:
                        skipped["dimension: _%s_" % dimension] += 1
                        continue
                    member = enum[1].get(value_name)
                    if member is None:
                        skipped["value: _%s_%s" % (dimension, value_name)] += 1
                        continue
                    metric.setdefault("dim", dimension)
                    metric.setdefault("cases", {})[member] = part


def merge_shorthands(table):
    """A one-value shorthand covers both axes; fold it into Block/Inline."""
    for component, metrics in table.items():
        for name in list(metrics):
            axes = [name + suffix for suffix in SHORTHAND[2]]
            if not any(axis in metrics for axis in axes):
                continue
            plain = metrics.pop(name)
            for axis in axes:
                target = metrics.setdefault(axis, {})
                if "base" in plain:
                    target.setdefault("base", plain["base"])
                for member, value in (plain.get("cases") or {}).items():
                    target.setdefault("dim", plain["dim"])
                    target.setdefault("cases", {}).setdefault(member, value)


def prune(table):
    for component in table:
        for name in list(table[component]):
            entry = table[component][name]
            if "cases" not in entry and "base" not in entry:
                del table[component][name]


def expand(raw_name, raw_value, root):
    """Yield (name suffix, px value) for a declaration, or nothing."""
    parts = split_values(raw_value.strip())
    if len(parts) == 1:
        length = as_length(parts[0], root)
        if length is not None:
            yield "", length
        return
    suffixes = SHORTHAND.get(len(parts))
    if not suffixes:
        return
    lengths = [as_length(p, root) for p in parts]
    if any(l is None for l in lengths):
        return
    for suffix, length in zip(suffixes, lengths):
        yield suffix, length


def emit(table, version):
    out = [HEADER.format(version=version)]
    out.append("""pragma Singleton
import QtQuick
import QGravityUI.Core

// Per-component metrics, read out of each component's --_--* block.
//
// Names are mechanical: the CSS block plus the custom property, so
// `.g-button_size_l { --_--padding: 16px }` is `buttonPadding(GSize.L)` and a
// two-part shorthand splits into ...Block and ...Inline the way CSS reads it.
// A metric that turns out to be the same for every modifier is a plain
// property instead of a one-armed switch.
//
// Metrics.qml is the friendlier face over this; use whichever fits.
QtObject {
""")

    for component in sorted(table):
        metrics = table[component]
        if not metrics:
            continue
        out.append("    // --- %s %s\n"
                   % (component, "-" * max(0, 58 - len(component))))
        for name in sorted(metrics):
            entry = metrics[name]
            full = component + name
            cases = entry.get("cases") or {}
            values = list(cases.values())
            if "base" in entry:
                values.append(entry["base"])
            kind = "int" if all(float(v).is_integer() for v in values) else "real"

            if not cases:
                out.append("    readonly property %s %s: %s\n\n"
                           % (kind, full, number(entry["base"])))
                continue

            enum_type = ENUMS[entry["dim"]][0]
            order = [m for m in ENUM_ORDER[enum_type] if m in cases]
            # The base block's value is the natural default; without one the
            # commonest case becomes the default, which keeps the switch short.
            fallback = entry.get("base")
            if fallback is None:
                # M / Normal is the modifier a component omits, so it reads
                # best as the default arm.
                for preferred in ("M", "Normal"):
                    if preferred in cases:
                        fallback = cases[preferred]
                        break
            if fallback is None:
                fallback = collections.Counter(cases.values()).most_common(1)[0][0]
            explicit = [m for m in order if cases[m] != fallback]

            if not explicit:
                out.append("    readonly property %s %s: %s\n\n"
                           % (kind, full, number(fallback)))
                continue

            out.append("    function %s(%s: int): %s {\n"
                       % (full, entry["dim"], kind))
            out.append("        switch (%s) {\n" % entry["dim"])
            for member in explicit:
                out.append("        case %s.%s: return %s;\n"
                           % (enum_type, member, number(cases[member])))
            out.append("        default: return %s;\n" % number(fallback))
            out.append("        }\n    }\n\n")

    out.append("}\n")
    return "".join(out)


ENUM_ORDER = {
    "GSize": ["Xxxs", "Xxs", "Xs", "S", "M", "L", "Xl"],
    "GView": ["Normal", "Action", "Raised", "Outlined", "Flat", "Filled", "Clear"],
    "GTheme": ["Normal", "Info", "Success", "Warning", "Danger", "Utility",
               "Unknown", "Clear", "Brand", "Misc"],
    "GDirection": ["Horizontal", "Vertical"],
    "GShape": ["Circle", "Square"],
}


def read_version(package):
    import json
    with open(os.path.join(package, "package.json"), encoding="utf-8") as fh:
        return json.load(fh)["version"]


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--package", required=True)
    parser.add_argument("--out", default=os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "..", "..",
        "src", "Tokens", "ComponentMetrics.qml"))
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--report-skipped", action="store_true",
                        help="list what could not be typed and why")
    args = parser.parse_args()

    version = read_version(args.package)
    table, skipped = collect(args.package)
    content = emit(table, version)
    out = os.path.abspath(args.out)

    if args.report_skipped:
        for reason, count in skipped.most_common():
            print("skipped %3d  %s" % (count, reason), file=sys.stderr)

    existing = None
    if os.path.exists(out):
        with open(out, encoding="utf-8", newline="") as fh:
            existing = fh.read()

    if args.check:
        if existing != content:
            print("src/Tokens/ComponentMetrics.qml is out of date", file=sys.stderr)
            return 1
        print("generated component metrics are up to date")
        return 0

    with open(out, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(content)
    total = sum(len(m) for m in table.values())
    print("wrote %d metrics across %d components (%d declarations skipped)"
          % (total, len(table), sum(skipped.values())))
    return 0


if __name__ == "__main__":
    sys.exit(main())
