#!/usr/bin/env python3
"""Generate the QML color tokens from @gravity-ui/uikit's compiled stylesheet.

    npm pack @gravity-ui/uikit@7.49.0 && tar xzf gravity-ui-uikit-7.49.0.tgz
    python tools/gen-tokens/gen_tokens.py --package ./package

Writes src/Tokens/ColorTokens.qml plus one src/Tokens/Theme<Name>.qml per theme.
Those files are generated -- edit this script, not them. Keep them committed so
building the project never needs npm.

styles.css holds a shared .g-root block and one .g-root_theme_<name> block per
theme. Semantic tokens are defined in terms of a private numbered palette via
var(), sometimes several levels deep, so values are resolved down to a literal
rgb()/rgba() before being emitted.
"""

import argparse
import os
import re
import sys

PREFIX = "--g-color-"


def read_block(src, start):
    """Return the text inside the brace-balanced block that follows `start`."""
    i = src.index("{", start)
    depth = 0
    for j in range(i, len(src)):
        if src[j] == "{":
            depth += 1
        elif src[j] == "}":
            depth -= 1
            if depth == 0:
                return src[i + 1:j]
    raise ValueError("unbalanced block")


def declarations(text):
    return {m.group(1): m.group(2).strip()
            for m in re.finditer(r'(--[\w-]+)\s*:\s*([^;]+);', text)}


def resolve(name, table, root, depth=0):
    """Expand var() chains until the value is a literal."""
    if depth > 16:
        raise ValueError("var() cycle at %s" % name)
    value = table.get(name, root.get(name))
    if value is None:
        return None
    while True:
        m = re.search(r'var\(\s*(--[\w-]+)\s*(?:,\s*([^()]*))?\)', value)
        if not m:
            return value.strip()
        inner = resolve(m.group(1), table, root, depth + 1)
        if inner is None:
            inner = (m.group(2) or "").strip()
        value = value[:m.start()] + inner + value[m.end():]


def qml_name(css_name):
    parts = css_name[len(PREFIX):].split("-")
    return parts[0] + "".join(p.capitalize() for p in parts[1:])


def channel(v):
    """255 -> 1, 0 -> 0, otherwise an exact fraction QML evaluates once."""
    n = int(v)
    if n == 0:
        return "0"
    if n == 255:
        return "1"
    return "%d / 255" % n


def qml_value(css_value):
    m = re.fullmatch(r'rgb\(\s*(\d+),\s*(\d+),\s*(\d+)\s*\)', css_value)
    if m:
        return '"#%02X%02X%02X"' % tuple(int(g) for g in m.groups())
    m = re.fullmatch(r'rgba\(\s*(\d+),\s*(\d+),\s*(\d+),\s*([\d.]+)\s*\)', css_value)
    if m:
        r, g, b, a = m.groups()
        return "Qt.rgba(%s, %s, %s, %s)" % (channel(r), channel(g), channel(b), a)
    raise ValueError("unsupported color form: %r" % css_value)


def theme_type_name(theme):
    # "light-hc" -> "ThemeLightHc"
    return "Theme" + "".join(p.capitalize() for p in theme.split("-"))


BANNER = ("// GENERATED by tools/gen-tokens/gen_tokens.py from "
          "@gravity-ui/uikit %s. Do not edit by hand.\n")


def emit_color_tokens(names, version):
    out = [BANNER % version, "import QtQuick\n",
           "// One resolved Gravity theme: every --g-color-* semantic token, with the",
           "// name mechanically derived from the CSS custom property.",
           "//",
           "// Declared as a real QML type rather than an inline QtObject so that qmllint",
           "// checks Theme.colors.<token> and the QML compiler can turn those lookups",
           "// into C++. Not named Palette: QtQuick already exports that name.",
           "QtObject {"]
    group = None
    for css in names:
        g = css[len(PREFIX):].split("-")[0]
        if g != group:
            group = g
            out.append("")
            out.append("    // %s%s-*" % (PREFIX, g))
        out.append("    property color %s" % qml_name(css))
    out.append("}")
    return "\n".join(out) + "\n"


def emit_theme(theme, names, table, root, version):
    out = [BANNER % version, "import QtQuick\n",
           "// .g-root_theme_%s" % theme,
           "ColorTokens {"]
    group = None
    for css in names:
        g = css[len(PREFIX):].split("-")[0]
        if g != group:
            group = g
            out.append("")
        value = resolve(css, table, root)
        out.append("    %s: %s" % (qml_name(css), qml_value(value)))
    out.append("}")
    return "\n".join(out) + "\n"


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    repo = os.path.abspath(os.path.join(here, "..", ".."))
    ap = argparse.ArgumentParser()
    ap.add_argument("--package", default=os.path.join(repo, "node_modules", "@gravity-ui", "uikit"),
                    help="unpacked @gravity-ui/uikit package directory")
    ap.add_argument("--out", default=os.path.join(repo, "src", "Tokens"))
    ap.add_argument("--check", action="store_true",
                    help="fail if the generated files differ from what is on disk")
    args = ap.parse_args()

    css_path = os.path.join(args.package, "styles", "styles.css")
    if not os.path.exists(css_path):
        sys.exit("no styles.css under %s -- pass --package" % args.package)

    version = "unknown"
    pkg_json = os.path.join(args.package, "package.json")
    if os.path.exists(pkg_json):
        import json
        version = json.load(open(pkg_json, encoding="utf-8")).get("version", version)

    src = open(css_path, encoding="utf-8").read()
    root = declarations(read_block(src, src.index(".g-root")))
    themes = {m.group(1): declarations(read_block(src, m.start()))
              for m in re.finditer(r'\.g-root_theme_([a-z-]+)\s*\{', src)}
    if not themes:
        sys.exit("no .g-root_theme_* blocks found")

    names = sorted({n for t in themes.values() for n in t
                    if n.startswith(PREFIX) and "-private-" not in n})

    files = {"ColorTokens.qml": emit_color_tokens(names, version)}
    for theme, table in sorted(themes.items()):
        files[theme_type_name(theme) + ".qml"] = emit_theme(theme, names, table, root, version)

    stale = []
    for fname, text in files.items():
        path = os.path.join(args.out, fname)
        old = open(path, encoding="utf-8").read() if os.path.exists(path) else None
        if old == text:
            continue
        if args.check:
            stale.append(fname)
        else:
            open(path, "w", encoding="utf-8", newline="\n").write(text)

    if args.check:
        if stale:
            sys.exit("stale generated files, re-run gen_tokens.py: " + ", ".join(sorted(stale)))
        print("generated token files are up to date")
    else:
        print("%d tokens x %d themes -> %s" % (len(names), len(themes), args.out))
        for fname in sorted(files):
            print("  " + fname)


if __name__ == "__main__":
    main()
