#!/usr/bin/env python3
"""Bundle @gravity-ui/icons into the QGravityUI.Icons QML module.

    npm pack @gravity-ui/icons@2.22.0 && tar xzf gravity-ui-icons-2.22.0.tgz
    python tools/gen-icons/gen_icons.py --package ./package
    python tools/gen-icons/gen_icons.py --package ./package --check   # for CI

The SVGs are copied verbatim: every one of them is a 16x16 viewBox painted
with fill="currentColor", which is exactly what GIcon's recolouring expects,
so there is nothing to rewrite. What is generated around them is the catalogue
(IconCatalog.qml) and the file list CMake needs (icons.cmake) -- both derived
from the directory listing, so adding an icon upstream is a re-run rather than
an edit.
"""

import argparse
import json
import os
import shutil
import sys

HEADER = ("// GENERATED by tools/gen-icons/gen_icons.py from "
          "@gravity-ui/icons {version}. Do not edit by hand.\n")


def read_version(package):
    with open(os.path.join(package, "package.json"), encoding="utf-8") as fh:
        return json.load(fh)["version"]


def icon_names(package):
    svg_dir = os.path.join(package, "svgs")
    names = [f[:-4] for f in os.listdir(svg_dir) if f.endswith(".svg")]
    names.sort()
    return names


def catalog_qml(names, version):
    lines = [HEADER.format(version=version)]
    lines.append("import QtQuick\n")
    lines.append("""
// Every icon name in the bundle, sorted. Kept as data rather than baked into
// Icons.qml so the singleton's logic stays hand-written and reviewable.
QtObject {
    readonly property var names: [
""")
    for name in names:
        lines.append('        "%s",\n' % name)
    lines.append("    ]\n}\n")
    return "".join(lines)


def cmake_list(names, version):
    lines = [HEADER.format(version=version).replace("//", "#")]
    lines.append("set(GRAVITY_ICON_FILES\n")
    for name in names:
        lines.append("    svgs/%s.svg\n" % name)
    lines.append(")\n")
    return "".join(lines)


def write(path, content, check, problems):
    existing = None
    if os.path.exists(path):
        with open(path, encoding="utf-8", newline="") as fh:
            existing = fh.read()
    if existing == content:
        return
    if check:
        problems.append(path)
        return
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(content)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--package", required=True,
                        help="unpacked @gravity-ui/icons package directory")
    parser.add_argument("--out", default=os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "..", "..", "src", "Icons"))
    parser.add_argument("--check", action="store_true",
                        help="fail instead of writing when anything differs")
    args = parser.parse_args()

    out = os.path.abspath(args.out)
    svg_out = os.path.join(out, "svgs")
    version = read_version(args.package)
    names = icon_names(args.package)
    problems = []

    if not args.check:
        # Rebuild the directory so icons dropped upstream do not linger.
        if os.path.isdir(svg_out):
            shutil.rmtree(svg_out)
        os.makedirs(svg_out)

    for name in names:
        src = os.path.join(args.package, "svgs", name + ".svg")
        dst = os.path.join(svg_out, name + ".svg")
        with open(src, encoding="utf-8", newline="") as fh:
            content = fh.read()
        write(dst, content, args.check, problems)

    if args.check:
        present = set(icon_names(out)) if os.path.isdir(svg_out) else set()
        for stale in sorted(present - set(names)):
            problems.append(os.path.join(svg_out, stale + ".svg") + " (stale)")

    write(os.path.join(out, "IconCatalog.qml"), catalog_qml(names, version),
          args.check, problems)
    write(os.path.join(out, "icons.cmake"), cmake_list(names, version),
          args.check, problems)

    with open(os.path.join(args.package, "LICENSE"), encoding="utf-8",
              newline="") as fh:
        licence = fh.read()
    write(os.path.join(out, "ICONS-LICENSE.txt"), licence, args.check, problems)

    if args.check:
        if problems:
            print("generated icon files are out of date:", file=sys.stderr)
            for path in problems[:20]:
                print("  " + path, file=sys.stderr)
            if len(problems) > 20:
                print("  ... and %d more" % (len(problems) - 20), file=sys.stderr)
            return 1
        print("generated icon files are up to date (%d icons)" % len(names))
    else:
        print("wrote %d icons from @gravity-ui/icons %s" % (len(names), version))
    return 0


if __name__ == "__main__":
    sys.exit(main())
