// GENERATED by tools/gen-tokens/gen_tokens.py from @gravity-ui/uikit 7.49.0. Do not edit by hand.

import QtQuick

// One resolved Gravity theme: every --g-color-* semantic token, with the
// name mechanically derived from the CSS custom property.
//
// Declared as a real QML type rather than an inline QtObject so that qmllint
// checks Theme.colors.<token> and the QML compiler can turn those lookups
// into C++. Not named Palette: QtQuick already exports that name.
QtObject {

    // --g-color-base-*
    property color baseBackground
    property color baseBrand
    property color baseBrandHover
    property color baseDangerHeavy
    property color baseDangerHeavyHover
    property color baseDangerLight
    property color baseDangerLightHover
    property color baseDangerMedium
    property color baseDangerMediumHover
    property color baseFloat
    property color baseFloatAccent
    property color baseFloatAccentHover
    property color baseFloatAnnouncement
    property color baseFloatHeavy
    property color baseFloatHover
    property color baseFloatMedium
    property color baseGeneric
    property color baseGenericAccent
    property color baseGenericAccentDisabled
    property color baseGenericHover
    property color baseGenericMedium
    property color baseGenericMediumHover
    property color baseGenericUltralight
    property color baseInfoHeavy
    property color baseInfoHeavyHover
    property color baseInfoLight
    property color baseInfoLightHover
    property color baseInfoMedium
    property color baseInfoMediumHover
    property color baseLight
    property color baseLightAccentDisabled
    property color baseLightDisabled
    property color baseLightHover
    property color baseLightSimpleHover
    property color baseMiscHeavy
    property color baseMiscHeavyHover
    property color baseMiscLight
    property color baseMiscLightHover
    property color baseMiscMedium
    property color baseMiscMediumHover
    property color baseModal
    property color baseNeutralHeavy
    property color baseNeutralHeavyHover
    property color baseNeutralLight
    property color baseNeutralLightHover
    property color baseNeutralMedium
    property color baseNeutralMediumHover
    property color basePositiveHeavy
    property color basePositiveHeavyHover
    property color basePositiveLight
    property color basePositiveLightHover
    property color basePositiveMedium
    property color basePositiveMediumHover
    property color baseSelection
    property color baseSelectionHover
    property color baseSimpleHover
    property color baseSimpleHoverSolid
    property color baseUtilityHeavy
    property color baseUtilityHeavyHover
    property color baseUtilityLight
    property color baseUtilityLightHover
    property color baseUtilityMedium
    property color baseUtilityMediumHover
    property color baseWarningHeavy
    property color baseWarningHeavyHover
    property color baseWarningLight
    property color baseWarningLightHover
    property color baseWarningMedium
    property color baseWarningMediumHover

    // --g-color-infographics-*
    property color infographicsAxis
    property color infographicsTooltipBg

    // --g-color-line-*
    property color lineBrand
    property color lineDanger
    property color lineFocus
    property color lineGeneric
    property color lineGenericAccent
    property color lineGenericAccentHover
    property color lineGenericActive
    property color lineGenericHover
    property color lineGenericSolid
    property color lineInfo
    property color lineLight
    property color lineMisc
    property color linePositive
    property color lineUtility
    property color lineWarning

    // --g-color-scroll-*
    property color scrollCorner
    property color scrollHandle
    property color scrollHandleHover
    property color scrollTrack

    // --g-color-sfx-*
    property color sfxFade
    property color sfxShadow
    property color sfxShadowHeavy
    property color sfxShadowLight
    property color sfxVeil

    // --g-color-text-*
    property color textBrand
    property color textBrandContrast
    property color textBrandHeavy
    property color textComplementary
    property color textDanger
    property color textDangerHeavy
    property color textDarkComplementary
    property color textDarkHint
    property color textDarkPrimary
    property color textDarkSecondary
    property color textHint
    property color textInfo
    property color textInfoHeavy
    property color textInvertedComplementary
    property color textInvertedHint
    property color textInvertedPrimary
    property color textInvertedSecondary
    property color textLightComplementary
    property color textLightHint
    property color textLightPrimary
    property color textLightSecondary
    property color textLink
    property color textLinkHover
    property color textLinkVisited
    property color textLinkVisitedHover
    property color textMisc
    property color textMiscHeavy
    property color textPositive
    property color textPositiveHeavy
    property color textPrimary
    property color textSecondary
    property color textUtility
    property color textUtilityHeavy
    property color textWarning
    property color textWarningHeavy
}
