// GENERATED by tools/gen-metrics/gen_metrics.py from @gravity-ui/uikit 7.49.0. Do not edit by hand.
pragma Singleton
import QtQuick
import QGravityUI.Core

// Per-component metrics, read out of each component's --_--* block.
//
// Names are mechanical: the CSS block plus the custom property, so
// `.g-button_size_l { --_--padding: 16px }` is `buttonPadding(GSize.L)` and a
// two-part shorthand splits into ...Block and ...Inline the way CSS reads it.
// A metric that turns out to be the same for every modifier is a plain
// property instead of a one-armed switch.
//
// Metrics.qml is the friendlier face over this; use whichever fits.
QtObject {
    // --- accordionItem ---------------------------------------------
    function accordionItemPaddingInline(size: int): int {
        switch (size) {
        case GSize.L: return 12;
        case GSize.Xl: return 12;
        default: return 8;
        }
    }

    // --- accordionSummary ------------------------------------------
    function accordionSummaryPaddingInline(size: int): int {
        switch (size) {
        case GSize.L: return 12;
        case GSize.Xl: return 12;
        default: return 8;
        }
    }

    // --- alert -----------------------------------------------------
    function alertBorderRadius(size: int): int {
        switch (size) {
        case GSize.S: return 6;
        case GSize.L: return 12;
        default: return 8;
        }
    }

    function alertCloseBtnMargin(size: int): int {
        switch (size) {
        case GSize.S: return 20;
        case GSize.L: return 6;
        default: return 12;
        }
    }

    function alertContentGap(size: int): int {
        switch (size) {
        case GSize.S: return 8;
        default: return 20;
        }
    }

    function alertIconMarginInlineEnd(size: int): int {
        switch (size) {
        case GSize.M: return 12;
        case GSize.L: return 16;
        default: return 8;
        }
    }

    function alertMessageFontSize(size: int): int {
        switch (size) {
        case GSize.L: return 15;
        default: return 13;
        }
    }

    readonly property int alertMessageFontWeight: 400

    function alertMessageLineHeight(size: int): int {
        switch (size) {
        case GSize.L: return 20;
        default: return 18;
        }
    }

    function alertMessageTitleIndent(size: int): int {
        switch (size) {
        case GSize.S: return 0;
        case GSize.L: return 8;
        default: return 4;
        }
    }

    function alertPaddingBlock(size: int): int {
        switch (size) {
        case GSize.S: return 11;
        case GSize.L: return 24;
        default: return 16;
        }
    }

    function alertPaddingInline(size: int): int {
        switch (size) {
        case GSize.S: return 12;
        case GSize.L: return 24;
        default: return 20;
        }
    }

    function alertTitleFontSize(size: int): int {
        switch (size) {
        case GSize.S: return 13;
        case GSize.L: return 17;
        default: return 15;
        }
    }

    readonly property int alertTitleFontWeight: 600

    function alertTitleLineHeight(size: int): int {
        switch (size) {
        case GSize.S: return 18;
        case GSize.L: return 24;
        default: return 20;
        }
    }

    // --- avatar ----------------------------------------------------
    function avatarBorderWidth(size: int): real {
        switch (size) {
        case GSize.Xxxs: return 1.5;
        case GSize.Xxs: return 1.5;
        default: return 2;
        }
    }

    function avatarFontSize(size: int): int {
        switch (size) {
        case GSize.Xxxs: return 9;
        case GSize.Xxs: return 9;
        case GSize.Xs: return 9;
        case GSize.S: return 11;
        case GSize.Xl: return 15;
        default: return 13;
        }
    }

    function avatarFontWeight(size: int): int {
        switch (size) {
        case GSize.M: return 600;
        case GSize.L: return 600;
        case GSize.Xl: return 600;
        default: return 400;
        }
    }

    function avatarInnerBorderWidth(size: int): real {
        switch (size) {
        case GSize.Xxxs: return 2.5;
        case GSize.Xxs: return 2.5;
        default: return 3;
        }
    }

    function avatarLineHeight(size: int): int {
        switch (size) {
        case GSize.Xxxs: return 12;
        case GSize.Xxs: return 12;
        case GSize.Xs: return 12;
        case GSize.S: return 16;
        case GSize.Xl: return 20;
        default: return 18;
        }
    }

    function avatarSize(size: int): int {
        switch (size) {
        case GSize.Xxxs: return 16;
        case GSize.Xxs: return 20;
        case GSize.Xs: return 24;
        case GSize.S: return 28;
        case GSize.L: return 42;
        case GSize.Xl: return 50;
        default: return 32;
        }
    }

    // --- avatarStack -----------------------------------------------
    readonly property int avatarStackMoreButtonBorderWidth: 1

    readonly property int avatarStackMoreButtonSize: 32

    // --- button ----------------------------------------------------
    function buttonBorderRadius(size: int): int {
        switch (size) {
        case GSize.Xs: return 3;
        case GSize.S: return 5;
        case GSize.L: return 8;
        case GSize.Xl: return 10;
        default: return 6;
        }
    }

    function buttonBorderWidth(view: int): int {
        switch (view) {
        case GView.Outlined: return 1;
        default: return 0;
        }
    }

    function buttonFocusOutlineOffset(view: int): int {
        switch (view) {
        case GView.Action: return 1;
        default: return 0;
        }
    }

    function buttonFontSize(size: int): int {
        switch (size) {
        case GSize.Xl: return 15;
        default: return 13;
        }
    }

    function buttonHeight(size: int): int {
        switch (size) {
        case GSize.Xs: return 20;
        case GSize.S: return 24;
        case GSize.L: return 36;
        case GSize.Xl: return 44;
        default: return 28;
        }
    }

    function buttonIconOffset(size: int): int {
        switch (size) {
        case GSize.Xs: return 4;
        case GSize.S: return 4;
        case GSize.Xl: return 12;
        default: return 8;
        }
    }

    function buttonIconSpace(size: int): int {
        switch (size) {
        case GSize.Xs: return 12;
        case GSize.Xl: return 20;
        default: return 16;
        }
    }

    function buttonPadding(size: int): int {
        switch (size) {
        case GSize.Xs: return 6;
        case GSize.S: return 8;
        case GSize.L: return 16;
        case GSize.Xl: return 24;
        default: return 12;
        }
    }

    // --- card ------------------------------------------------------
    function cardBorderRadius(size: int): int {
        switch (size) {
        case GSize.L: return 16;
        default: return 8;
        }
    }

    function cardBorderWidth(view: int): int {
        switch (view) {
        case GView.Outlined: return 1;
        default: return 0;
        }
    }

    // --- definitionList --------------------------------------------
    readonly property int definitionListCopyButton: 28

    readonly property int definitionListItemBlockStart: 16

    readonly property int definitionListTermWidth: 300

    // --- dialog ----------------------------------------------------
    readonly property int dialogCloseButtonSpace: 0

    readonly property int dialogSidePadding: 32

    function dialogWidth(size: int): int {
        switch (size) {
        case GSize.S: return 480;
        case GSize.L: return 900;
        default: return 720;
        }
    }

    // --- divider ---------------------------------------------------
    readonly property int dividerContentGap: 8

    readonly property int dividerSize: 1

    // --- helpMark --------------------------------------------------
    function helpMarkSize(size: int): int {
        switch (size) {
        case GSize.S: return 14;
        case GSize.L: return 18;
        case GSize.Xl: return 20;
        default: return 16;
        }
    }

    // --- label -----------------------------------------------------
    function labelBorderRadius(size: int): int {
        switch (size) {
        case GSize.Xxs: return 3;
        case GSize.Xs: return 3;
        case GSize.S: return 5;
        default: return 6;
        }
    }

    function labelHeight(size: int): int {
        switch (size) {
        case GSize.Xxs: return 18;
        case GSize.Xs: return 20;
        case GSize.S: return 24;
        default: return 28;
        }
    }

    function labelMarginAddonEnd(size: int): int {
        switch (size) {
        case GSize.Xxs: return 20;
        case GSize.Xs: return 22;
        case GSize.S: return 26;
        default: return 32;
        }
    }

    function labelMarginAddonStart(size: int): int {
        switch (size) {
        case GSize.Xxs: return 22;
        case GSize.Xs: return 24;
        case GSize.S: return 28;
        default: return 32;
        }
    }

    function labelMarginInline(size: int): int {
        switch (size) {
        case GSize.Xxs: return 6;
        case GSize.Xs: return 8;
        case GSize.S: return 10;
        default: return 12;
        }
    }

    // --- list ------------------------------------------------------
    readonly property int listItemPadding: 0

    // --- numberInput -----------------------------------------------
    function numberInputTextinputEndPadding(size: int): int {
        switch (size) {
        case GSize.L: return 3;
        case GSize.Xl: return 3;
        default: return 1;
        }
    }

    // --- numericArrows ---------------------------------------------
    readonly property int numericArrowsBorderWidth: 1

    // --- pinInput --------------------------------------------------
    function pinInputGap(size: int): int {
        switch (size) {
        case GSize.S: return 6;
        case GSize.L: return 10;
        case GSize.Xl: return 12;
        default: return 8;
        }
    }

    function pinInputItemWidth(size: int): int {
        switch (size) {
        case GSize.S: return 22;
        case GSize.L: return 34;
        case GSize.Xl: return 42;
        default: return 26;
        }
    }

    // --- popup -----------------------------------------------------
    readonly property int popupBorderRadius: 4

    readonly property int popupBorderWidth: 1

    // --- segmentedRadioGroup ---------------------------------------
    function segmentedRadioGroupBorderRadius(size: int): int {
        switch (size) {
        case GSize.S: return 5;
        case GSize.L: return 8;
        case GSize.Xl: return 10;
        default: return 6;
        }
    }

    readonly property int segmentedRadioGroupBorderWidth: 1

    // --- selectControl ---------------------------------------------
    function selectControlBorderRadius(size: int): int {
        switch (size) {
        case GSize.S: return 5;
        case GSize.L: return 8;
        case GSize.Xl: return 10;
        default: return 6;
        }
    }

    function selectControlTextRightPadding(size: int): int {
        switch (size) {
        case GSize.L: return 12;
        case GSize.Xl: return 12;
        default: return 8;
        }
    }

    // --- sheet -----------------------------------------------------
    readonly property int sheetTopHeight: 20

    // --- skeleton --------------------------------------------------
    function skeletonBorderRadius(size: int): int {
        switch (size) {
        case GSize.Xs: return 3;
        case GSize.M: return 6;
        case GSize.L: return 8;
        case GSize.Xl: return 10;
        default: return 5;
        }
    }

    function skeletonSize(size: int): int {
        switch (size) {
        case GSize.Xs: return 20;
        case GSize.S: return 24;
        case GSize.L: return 36;
        case GSize.Xl: return 44;
        default: return 28;
        }
    }

    // --- stepper ---------------------------------------------------
    readonly property int stepperTextMaxWidth: 180

    // --- tabList ---------------------------------------------------
    function tabListItemBorderWidth(size: int): int {
        switch (size) {
        case GSize.Xl: return 3;
        default: return 2;
        }
    }

    function tabListItemGap(size: int): int {
        switch (size) {
        case GSize.L: return 28;
        case GSize.Xl: return 32;
        default: return 24;
        }
    }

    function tabListItemHeight(size: int): int {
        switch (size) {
        case GSize.L: return 40;
        case GSize.Xl: return 44;
        default: return 36;
        }
    }

    // --- textArea --------------------------------------------------
    function textAreaBorderRadius(size: int): int {
        switch (size) {
        case GSize.S: return 5;
        case GSize.L: return 8;
        case GSize.Xl: return 10;
        default: return 6;
        }
    }

    readonly property int textAreaBorderWidth: 1

    // --- textInput -------------------------------------------------
    function textInputBorderRadius(size: int): int {
        switch (size) {
        case GSize.S: return 5;
        case GSize.L: return 8;
        case GSize.Xl: return 10;
        default: return 6;
        }
    }

    readonly property int textInputBorderWidth: 1

    function textInputErrorIconPaddingBlock(size: int): int {
        switch (size) {
        case GSize.L: return 9;
        case GSize.Xl: return 13;
        default: return 5;
        }
    }

    function textInputErrorIconPaddingInlineEnd(size: int): int {
        switch (size) {
        case GSize.L: return 9;
        case GSize.Xl: return 13;
        default: return 5;
        }
    }

    readonly property int textInputErrorIconPaddingInlineStart: 0

    // --- toast -----------------------------------------------------
    readonly property int toastItemGap: 10

    readonly property int toastItemPadding: 16

    // --- toaster ---------------------------------------------------
    readonly property int toasterWidth: 312

    // --- tooltip ---------------------------------------------------
    readonly property int tooltipBorderRadius: 4

    // --- user ------------------------------------------------------
    function userAvatarOffset(size: int): int {
        switch (size) {
        case GSize.Xxxs: return 6;
        case GSize.Xxs: return 6;
        case GSize.Xs: return 6;
        case GSize.S: return 6;
        case GSize.L: return 12;
        case GSize.Xl: return 12;
        default: return 8;
        }
    }

    readonly property int userDescriptionFontSize: 13

    readonly property int userDescriptionFontWeight: 400

    readonly property int userDescriptionLineHeight: 16

    function userNameFontSize(size: int): int {
        switch (size) {
        case GSize.Xl: return 15;
        default: return 13;
        }
    }

    readonly property int userNameFontWeight: 400

    function userNameLineHeight(size: int): int {
        switch (size) {
        case GSize.Xl: return 20;
        default: return 16;
        }
    }

    // --- userLabel -------------------------------------------------
    readonly property int userLabelBorderRadius: 25

    readonly property int userLabelDescriptionFontSize: 13

    readonly property int userLabelDescriptionFontWeight: 400

    readonly property int userLabelDescriptionLineHeight: 16

    function userLabelGap(size: int): int {
        switch (size) {
        case GSize.Xxxs: return 4;
        case GSize.Xxs: return 4;
        case GSize.M: return 8;
        case GSize.L: return 12;
        case GSize.Xl: return 16;
        default: return 6;
        }
    }

    function userLabelPadding(size: int): int {
        switch (size) {
        case GSize.Xxxs: return 6;
        case GSize.Xxs: return 6;
        case GSize.Xs: return 10;
        case GSize.L: return 16;
        case GSize.Xl: return 20;
        default: return 12;
        }
    }

    function userLabelSize(size: int): int {
        switch (size) {
        case GSize.Xxxs: return 16;
        case GSize.Xxs: return 20;
        case GSize.Xs: return 24;
        case GSize.M: return 32;
        case GSize.L: return 42;
        case GSize.Xl: return 50;
        default: return 28;
        }
    }

    function userLabelTextFontSize(size: int): int {
        switch (size) {
        case GSize.Xxxs: return 11;
        case GSize.Xxs: return 11;
        case GSize.Xs: return 11;
        case GSize.Xl: return 15;
        default: return 13;
        }
    }

    readonly property int userLabelTextFontWeight: 400

    function userLabelTextLineHeight(size: int): int {
        switch (size) {
        case GSize.Xl: return 20;
        default: return 16;
        }
    }

}
