// GENERATED by tools/gen-tokens/gen_tokens.py from @gravity-ui/uikit 7.49.0. Do not edit by hand.

import QtQuick

// .g-root_theme_dark-hc
ColorTokens {

    baseBackground: "#121112"
    baseBrand: "#FFBE5C"
    baseBrandHover: "#FFD28D"
    baseDangerHeavy: "#ED708E"
    baseDangerHeavyHover: "#F5ADBE"
    baseDangerLight: Qt.rgba(229 / 255, 50 / 255, 93 / 255, 0.4)
    baseDangerLightHover: Qt.rgba(229 / 255, 50 / 255, 93 / 255, 0.7)
    baseDangerMedium: Qt.rgba(229 / 255, 50 / 255, 93 / 255, 0.8)
    baseDangerMediumHover: "#E8476D"
    baseFloat: "#2A292A"
    baseFloatAccent: "#595859"
    baseFloatAccentHover: "#717071"
    baseFloatAnnouncement: "#414141"
    baseFloatHeavy: "#595859"
    baseFloatHover: "#414141"
    baseFloatMedium: "#414141"
    baseGeneric: Qt.rgba(1, 1, 1, 0.1)
    baseGenericAccent: Qt.rgba(1, 1, 1, 0.2)
    baseGenericAccentDisabled: Qt.rgba(1, 1, 1, 0.15)
    baseGenericHover: Qt.rgba(1, 1, 1, 0.25)
    baseGenericMedium: Qt.rgba(1, 1, 1, 0.25)
    baseGenericMediumHover: Qt.rgba(1, 1, 1, 0.4)
    baseGenericUltralight: Qt.rgba(1, 1, 1, 0.05)
    baseInfoHeavy: "#72B6F5"
    baseInfoHeavyHover: "#AFD5F9"
    baseInfoLight: Qt.rgba(54 / 255, 151 / 255, 241 / 255, 0.4)
    baseInfoLightHover: Qt.rgba(54 / 255, 151 / 255, 241 / 255, 0.7)
    baseInfoMedium: Qt.rgba(54 / 255, 151 / 255, 241 / 255, 0.8)
    baseInfoMediumHover: "#4AA1F2"
    baseLight: Qt.rgba(1, 1, 1, 0.85)
    baseLightAccentDisabled: Qt.rgba(1, 1, 1, 0.3)
    baseLightDisabled: Qt.rgba(1, 1, 1, 0.15)
    baseLightHover: Qt.rgba(1, 1, 1, 0.7)
    baseLightSimpleHover: Qt.rgba(1, 1, 1, 0.15)
    baseMiscHeavy: "#90A6BA"
    baseMiscHeavyHover: "#BFCCD7"
    baseMiscLight: Qt.rgba(96 / 255, 128 / 255, 156 / 255, 0.4)
    baseMiscLightHover: Qt.rgba(96 / 255, 128 / 255, 156 / 255, 0.7)
    baseMiscMedium: Qt.rgba(96 / 255, 128 / 255, 156 / 255, 0.8)
    baseMiscMediumHover: "#708DA6"
    baseModal: "#121112"
    baseNeutralHeavy: Qt.rgba(1, 1, 1, 0.65)
    baseNeutralHeavyHover: Qt.rgba(1, 1, 1, 0.75)
    baseNeutralLight: Qt.rgba(1, 1, 1, 0.2)
    baseNeutralLightHover: Qt.rgba(1, 1, 1, 0.35)
    baseNeutralMedium: Qt.rgba(1, 1, 1, 0.4)
    baseNeutralMediumHover: Qt.rgba(1, 1, 1, 0.55)
    basePositiveHeavy: "#82C8B9"
    basePositiveHeavyHover: "#B8DFD7"
    basePositiveLight: Qt.rgba(77 / 255, 176 / 255, 155 / 255, 0.4)
    basePositiveLightHover: Qt.rgba(77 / 255, 176 / 255, 155 / 255, 0.7)
    basePositiveMedium: Qt.rgba(77 / 255, 176 / 255, 155 / 255, 0.8)
    basePositiveMediumHover: "#5FB8A5"
    baseSelection: Qt.rgba(1, 190 / 255, 92 / 255, 0.4)
    baseSelectionHover: Qt.rgba(1, 190 / 255, 92 / 255, 0.7)
    baseSimpleHover: Qt.rgba(1, 1, 1, 0.25)
    baseSimpleHoverSolid: "#4D4D4D"
    baseUtilityHeavy: "#B186DB"
    baseUtilityHeavyHover: "#D2BAEB"
    baseUtilityLight: Qt.rgba(143 / 255, 82 / 255, 204 / 255, 0.4)
    baseUtilityLightHover: Qt.rgba(143 / 255, 82 / 255, 204 / 255, 0.7)
    baseUtilityMedium: Qt.rgba(143 / 255, 82 / 255, 204 / 255, 0.8)
    baseUtilityMediumHover: "#9A63D1"
    baseWarningHeavy: "#FFD28D"
    baseWarningHeavyHover: "#FFE5BE"
    baseWarningLight: Qt.rgba(1, 190 / 255, 92 / 255, 0.4)
    baseWarningLightHover: Qt.rgba(1, 190 / 255, 92 / 255, 0.7)
    baseWarningMedium: Qt.rgba(1, 190 / 255, 92 / 255, 0.8)
    baseWarningMediumHover: "#FFC56C"

    infographicsAxis: "#363536"
    infographicsTooltipBg: Qt.rgba(56 / 255, 57 / 255, 60 / 255, 0.97)

    lineBrand: "#FFC56C"
    lineDanger: "#E5325D"
    lineFocus: "#60809C"
    lineGeneric: Qt.rgba(1, 1, 1, 0.15)
    lineGenericAccent: Qt.rgba(1, 1, 1, 0.35)
    lineGenericAccentHover: Qt.rgba(1, 1, 1, 0.8)
    lineGenericActive: Qt.rgba(1, 1, 1, 0.6)
    lineGenericHover: Qt.rgba(1, 1, 1, 0.25)
    lineGenericSolid: "#363536"
    lineInfo: "#3697F1"
    lineLight: Qt.rgba(1, 1, 1, 0.5)
    lineMisc: "#60809C"
    linePositive: "#4DB09B"
    lineUtility: "#8F52CC"
    lineWarning: "#FFBE5C"

    scrollCorner: Qt.rgba(1, 1, 1, 0.15)
    scrollHandle: Qt.rgba(1, 1, 1, 0.15)
    scrollHandleHover: Qt.rgba(1, 1, 1, 0.25)
    scrollTrack: "#121112"

    sfxFade: Qt.rgba(1, 1, 1, 0.25)
    sfxShadow: Qt.rgba(0, 0, 0, 0.2)
    sfxShadowHeavy: Qt.rgba(0, 0, 0, 0.4)
    sfxShadowLight: Qt.rgba(0, 0, 0, 0.2)
    sfxVeil: Qt.rgba(0, 0, 0, 0.7)

    textBrand: "#FFC56C"
    textBrandContrast: "#000000"
    textBrandHeavy: "#FFD28D"
    textComplementary: Qt.rgba(1, 1, 1, 0.8)
    textDanger: "#EA5B7D"
    textDangerHeavy: "#F5ADBE"
    textDarkComplementary: Qt.rgba(0, 0, 0, 0.8)
    textDarkHint: Qt.rgba(0, 0, 0, 0.4)
    textDarkPrimary: "#000000"
    textDarkSecondary: Qt.rgba(0, 0, 0, 0.6)
    textHint: Qt.rgba(1, 1, 1, 0.4)
    textInfo: "#5EACF4"
    textInfoHeavy: "#AFD5F9"
    textInvertedComplementary: Qt.rgba(0, 0, 0, 0.8)
    textInvertedHint: Qt.rgba(0, 0, 0, 0.4)
    textInvertedPrimary: "#000000"
    textInvertedSecondary: Qt.rgba(0, 0, 0, 0.6)
    textLightComplementary: Qt.rgba(1, 1, 1, 0.8)
    textLightHint: Qt.rgba(1, 1, 1, 0.4)
    textLightPrimary: "#FFFFFF"
    textLightSecondary: Qt.rgba(1, 1, 1, 0.6)
    textLink: "#FFBE5C"
    textLinkHover: "#C8630C"
    textLinkVisited: "#A575D6"
    textLinkVisitedHover: "#C7A9E6"
    textMisc: "#8099B0"
    textMiscHeavy: "#BFCCD7"
    textPositive: "#71C0AF"
    textPositiveHeavy: "#B8DFD7"
    textPrimary: "#FFFFFF"
    textSecondary: Qt.rgba(1, 1, 1, 0.6)
    textUtility: "#A575D6"
    textUtilityHeavy: "#D2BAEB"
    textWarning: "#FFCB7D"
    textWarningHeavy: "#FFE5BE"
}
