// GENERATED by tools/gen-tokens/gen_tokens.py from @gravity-ui/uikit 7.49.0. Do not edit by hand.

import QtQuick

// .g-root_theme_dark
ColorTokens {

    baseBackground: "#221D22"
    baseBrand: "#FFBE5C"
    baseBrandHover: "#FFCB7D"
    baseDangerHeavy: "#E8476D"
    baseDangerHeavyHover: "#ED708E"
    baseDangerLight: Qt.rgba(229 / 255, 50 / 255, 93 / 255, 0.2)
    baseDangerLightHover: Qt.rgba(229 / 255, 50 / 255, 93 / 255, 0.3)
    baseDangerMedium: Qt.rgba(229 / 255, 50 / 255, 93 / 255, 0.5)
    baseDangerMediumHover: Qt.rgba(229 / 255, 50 / 255, 93 / 255, 0.7)
    baseFloat: "#383438"
    baseFloatAccent: "#433F43"
    baseFloatAccentHover: "#4E4A4E"
    baseFloatAnnouncement: "#433F43"
    baseFloatHeavy: "#595559"
    baseFloatHover: "#433F43"
    baseFloatMedium: "#433F43"
    baseGeneric: Qt.rgba(1, 1, 1, 0.1)
    baseGenericAccent: Qt.rgba(1, 1, 1, 0.15)
    baseGenericAccentDisabled: Qt.rgba(1, 1, 1, 0.07)
    baseGenericHover: Qt.rgba(1, 1, 1, 0.15)
    baseGenericMedium: Qt.rgba(1, 1, 1, 0.25)
    baseGenericMediumHover: Qt.rgba(1, 1, 1, 0.3)
    baseGenericUltralight: "#262226"
    baseInfoHeavy: "#4AA1F2"
    baseInfoHeavyHover: "#72B6F5"
    baseInfoLight: Qt.rgba(54 / 255, 151 / 255, 241 / 255, 0.2)
    baseInfoLightHover: Qt.rgba(54 / 255, 151 / 255, 241 / 255, 0.3)
    baseInfoMedium: Qt.rgba(54 / 255, 151 / 255, 241 / 255, 0.5)
    baseInfoMediumHover: Qt.rgba(54 / 255, 151 / 255, 241 / 255, 0.7)
    baseLight: Qt.rgba(1, 1, 1, 0.85)
    baseLightAccentDisabled: Qt.rgba(1, 1, 1, 0.3)
    baseLightDisabled: Qt.rgba(1, 1, 1, 0.15)
    baseLightHover: Qt.rgba(1, 1, 1, 0.7)
    baseLightSimpleHover: Qt.rgba(1, 1, 1, 0.15)
    baseMiscHeavy: "#708DA6"
    baseMiscHeavyHover: "#90A6BA"
    baseMiscLight: Qt.rgba(96 / 255, 128 / 255, 156 / 255, 0.2)
    baseMiscLightHover: Qt.rgba(96 / 255, 128 / 255, 156 / 255, 0.3)
    baseMiscMedium: Qt.rgba(96 / 255, 128 / 255, 156 / 255, 0.5)
    baseMiscMediumHover: Qt.rgba(96 / 255, 128 / 255, 156 / 255, 0.7)
    baseModal: "#221D22"
    baseNeutralHeavy: Qt.rgba(1, 1, 1, 0.55)
    baseNeutralHeavyHover: Qt.rgba(1, 1, 1, 0.65)
    baseNeutralLight: Qt.rgba(1, 1, 1, 0.1)
    baseNeutralLightHover: Qt.rgba(1, 1, 1, 0.15)
    baseNeutralMedium: Qt.rgba(1, 1, 1, 0.25)
    baseNeutralMediumHover: Qt.rgba(1, 1, 1, 0.35)
    basePositiveHeavy: "#5FB8A5"
    basePositiveHeavyHover: "#82C8B9"
    basePositiveLight: Qt.rgba(77 / 255, 176 / 255, 155 / 255, 0.2)
    basePositiveLightHover: Qt.rgba(77 / 255, 176 / 255, 155 / 255, 0.3)
    basePositiveMedium: Qt.rgba(77 / 255, 176 / 255, 155 / 255, 0.5)
    basePositiveMediumHover: Qt.rgba(77 / 255, 176 / 255, 155 / 255, 0.7)
    baseSelection: Qt.rgba(1, 190 / 255, 92 / 255, 0.2)
    baseSelectionHover: Qt.rgba(1, 190 / 255, 92 / 255, 0.3)
    baseSimpleHover: Qt.rgba(1, 1, 1, 0.1)
    baseSimpleHoverSolid: "#383438"
    baseUtilityHeavy: "#9A63D1"
    baseUtilityHeavyHover: "#B186DB"
    baseUtilityLight: Qt.rgba(143 / 255, 82 / 255, 204 / 255, 0.2)
    baseUtilityLightHover: Qt.rgba(143 / 255, 82 / 255, 204 / 255, 0.4)
    baseUtilityMedium: Qt.rgba(143 / 255, 82 / 255, 204 / 255, 0.5)
    baseUtilityMediumHover: Qt.rgba(143 / 255, 82 / 255, 204 / 255, 0.7)
    baseWarningHeavy: "#FFC56C"
    baseWarningHeavyHover: "#FFD28D"
    baseWarningLight: Qt.rgba(1, 190 / 255, 92 / 255, 0.2)
    baseWarningLightHover: Qt.rgba(1, 190 / 255, 92 / 255, 0.3)
    baseWarningMedium: Qt.rgba(1, 190 / 255, 92 / 255, 0.5)
    baseWarningMediumHover: Qt.rgba(1, 190 / 255, 92 / 255, 0.7)

    infographicsAxis: "#433F43"
    infographicsTooltipBg: Qt.rgba(76 / 255, 75 / 255, 81 / 255, 0.95)

    lineBrand: "#FFC56C"
    lineDanger: Qt.rgba(229 / 255, 50 / 255, 93 / 255, 0.8)
    lineFocus: Qt.rgba(96 / 255, 128 / 255, 156 / 255, 0.8)
    lineGeneric: Qt.rgba(1, 1, 1, 0.15)
    lineGenericAccent: Qt.rgba(1, 1, 1, 0.15)
    lineGenericAccentHover: Qt.rgba(1, 1, 1, 0.3)
    lineGenericActive: Qt.rgba(1, 1, 1, 0.3)
    lineGenericHover: Qt.rgba(1, 1, 1, 0.25)
    lineGenericSolid: "#433F43"
    lineInfo: Qt.rgba(54 / 255, 151 / 255, 241 / 255, 0.8)
    lineLight: Qt.rgba(1, 1, 1, 0.5)
    lineMisc: Qt.rgba(96 / 255, 128 / 255, 156 / 255, 0.8)
    linePositive: Qt.rgba(77 / 255, 176 / 255, 155 / 255, 0.8)
    lineUtility: Qt.rgba(143 / 255, 82 / 255, 204 / 255, 0.8)
    lineWarning: Qt.rgba(1, 190 / 255, 92 / 255, 0.8)

    scrollCorner: Qt.rgba(1, 1, 1, 0.15)
    scrollHandle: Qt.rgba(1, 1, 1, 0.15)
    scrollHandleHover: Qt.rgba(1, 1, 1, 0.25)
    scrollTrack: "#221D22"

    sfxFade: Qt.rgba(1, 1, 1, 0.25)
    sfxShadow: Qt.rgba(0, 0, 0, 0.2)
    sfxShadowHeavy: Qt.rgba(0, 0, 0, 0.5)
    sfxShadowLight: Qt.rgba(0, 0, 0, 0.2)
    sfxVeil: Qt.rgba(0, 0, 0, 0.6)

    textBrand: "#FFC56C"
    textBrandContrast: Qt.rgba(0, 0, 0, 0.9)
    textBrandHeavy: "#FFD28D"
    textComplementary: Qt.rgba(1, 1, 1, 0.7)
    textDanger: "#E5325D"
    textDangerHeavy: "#E8476D"
    textDarkComplementary: Qt.rgba(0, 0, 0, 0.7)
    textDarkHint: Qt.rgba(0, 0, 0, 0.3)
    textDarkPrimary: Qt.rgba(0, 0, 0, 0.9)
    textDarkSecondary: Qt.rgba(0, 0, 0, 0.5)
    textHint: Qt.rgba(1, 1, 1, 0.3)
    textInfo: "#3697F1"
    textInfoHeavy: "#4AA1F2"
    textInvertedComplementary: Qt.rgba(0, 0, 0, 0.7)
    textInvertedHint: Qt.rgba(0, 0, 0, 0.3)
    textInvertedPrimary: Qt.rgba(0, 0, 0, 0.9)
    textInvertedSecondary: Qt.rgba(0, 0, 0, 0.5)
    textLightComplementary: Qt.rgba(1, 1, 1, 0.7)
    textLightHint: Qt.rgba(1, 1, 1, 0.3)
    textLightPrimary: Qt.rgba(1, 1, 1, 0.85)
    textLightSecondary: Qt.rgba(1, 1, 1, 0.5)
    textLink: "#FFBE5C"
    textLinkHover: "#C8630C"
    textLinkVisited: "#9A63D1"
    textLinkVisitedHover: "#BC97E0"
    textMisc: "#708DA6"
    textMiscHeavy: "#8099B0"
    textPositive: "#4DB09B"
    textPositiveHeavy: "#5FB8A5"
    textPrimary: Qt.rgba(1, 1, 1, 0.85)
    textSecondary: Qt.rgba(1, 1, 1, 0.5)
    textUtility: "#9A63D1"
    textUtilityHeavy: "#A575D6"
    textWarning: "#FFBE5C"
    textWarningHeavy: "#FFC56C"
}
