// GENERATED by tools/gen-tokens/gen_tokens.py from @gravity-ui/uikit 7.49.0. Do not edit by hand.

import QtQuick

// .g-root_theme_light
ColorTokens {

    baseBackground: "#FFFFFF"
    baseBrand: "#FFBE5C"
    baseBrandHover: "#E9AE56"
    baseDangerHeavy: "#E9033A"
    baseDangerHeavyHover: "#BD0935"
    baseDangerLight: Qt.rgba(1, 0, 61 / 255, 0.15)
    baseDangerLightHover: Qt.rgba(1, 0, 61 / 255, 0.3)
    baseDangerMedium: Qt.rgba(1, 0, 61 / 255, 0.3)
    baseDangerMediumHover: Qt.rgba(1, 0, 61 / 255, 0.5)
    baseFloat: "#FFFFFF"
    baseFloatAccent: "#FFFFFF"
    baseFloatAccentHover: Qt.rgba(1, 1, 1, 0.85)
    baseFloatAnnouncement: "#F0F3F5"
    baseFloatHeavy: "#4C4C4C"
    baseFloatHover: "#F2F2F2"
    baseFloatMedium: "#737373"
    baseGeneric: Qt.rgba(0, 0, 0, 0.05)
    baseGenericAccent: Qt.rgba(0, 0, 0, 0.15)
    baseGenericAccentDisabled: Qt.rgba(0, 0, 0, 0.07)
    baseGenericHover: Qt.rgba(0, 0, 0, 0.15)
    baseGenericMedium: Qt.rgba(0, 0, 0, 0.15)
    baseGenericMediumHover: Qt.rgba(0, 0, 0, 0.25)
    baseGenericUltralight: "#FAFAFA"
    baseInfoHeavy: "#348BDC"
    baseInfoHeavyHover: "#3072B3"
    baseInfoLight: Qt.rgba(54 / 255, 151 / 255, 241 / 255, 0.15)
    baseInfoLightHover: Qt.rgba(54 / 255, 151 / 255, 241 / 255, 0.3)
    baseInfoMedium: Qt.rgba(54 / 255, 151 / 255, 241 / 255, 0.3)
    baseInfoMediumHover: Qt.rgba(54 / 255, 151 / 255, 241 / 255, 0.5)
    baseLight: "#FFFFFF"
    baseLightAccentDisabled: Qt.rgba(1, 1, 1, 0.3)
    baseLightDisabled: Qt.rgba(1, 1, 1, 0.15)
    baseLightHover: Qt.rgba(1, 1, 1, 0.85)
    baseLightSimpleHover: Qt.rgba(1, 1, 1, 0.15)
    baseMiscHeavy: "#647A8D"
    baseMiscHeavyHover: "#556575"
    baseMiscLight: Qt.rgba(107 / 255, 132 / 255, 153 / 255, 0.15)
    baseMiscLightHover: Qt.rgba(107 / 255, 132 / 255, 153 / 255, 0.3)
    baseMiscMedium: Qt.rgba(107 / 255, 132 / 255, 153 / 255, 0.3)
    baseMiscMediumHover: Qt.rgba(107 / 255, 132 / 255, 153 / 255, 0.5)
    baseModal: "#FFFFFF"
    baseNeutralHeavy: Qt.rgba(0, 0, 0, 0.45)
    baseNeutralHeavyHover: Qt.rgba(0, 0, 0, 0.55)
    baseNeutralLight: Qt.rgba(0, 0, 0, 0.05)
    baseNeutralLightHover: Qt.rgba(0, 0, 0, 0.1)
    baseNeutralMedium: Qt.rgba(0, 0, 0, 0.2)
    baseNeutralMediumHover: Qt.rgba(0, 0, 0, 0.25)
    basePositiveHeavy: "#30AA6E"
    basePositiveHeavyHover: "#2D8B5D"
    basePositiveLight: Qt.rgba(50 / 255, 186 / 255, 118 / 255, 0.15)
    basePositiveLightHover: Qt.rgba(50 / 255, 186 / 255, 118 / 255, 0.3)
    basePositiveMedium: Qt.rgba(50 / 255, 186 / 255, 118 / 255, 0.3)
    basePositiveMediumHover: Qt.rgba(50 / 255, 186 / 255, 118 / 255, 0.5)
    baseSelection: Qt.rgba(1, 190 / 255, 92 / 255, 0.3)
    baseSelectionHover: Qt.rgba(1, 190 / 255, 92 / 255, 0.5)
    baseSimpleHover: Qt.rgba(0, 0, 0, 0.05)
    baseSimpleHoverSolid: "#F2F2F2"
    baseUtilityHeavy: "#844DBB"
    baseUtilityHeavyHover: "#6E4299"
    baseUtilityLight: Qt.rgba(143 / 255, 82 / 255, 204 / 255, 0.15)
    baseUtilityLightHover: Qt.rgba(143 / 255, 82 / 255, 204 / 255, 0.3)
    baseUtilityMedium: Qt.rgba(143 / 255, 82 / 255, 204 / 255, 0.3)
    baseUtilityMediumHover: Qt.rgba(143 / 255, 82 / 255, 204 / 255, 0.5)
    baseWarningHeavy: "#FFBE5C"
    baseWarningHeavyHover: "#D39E50"
    baseWarningLight: Qt.rgba(1, 190 / 255, 92 / 255, 0.3)
    baseWarningLightHover: Qt.rgba(1, 190 / 255, 92 / 255, 0.5)
    baseWarningMedium: Qt.rgba(1, 190 / 255, 92 / 255, 0.7)
    baseWarningMediumHover: Qt.rgba(1, 190 / 255, 92 / 255, 0.9)

    infographicsAxis: "#D9D9D9"
    infographicsTooltipBg: Qt.rgba(1, 1, 1, 0.95)

    lineBrand: "#E9AE56"
    lineDanger: Qt.rgba(1, 0, 61 / 255, 0.8)
    lineFocus: Qt.rgba(107 / 255, 132 / 255, 153 / 255, 0.8)
    lineGeneric: Qt.rgba(0, 0, 0, 0.1)
    lineGenericAccent: Qt.rgba(0, 0, 0, 0.15)
    lineGenericAccentHover: Qt.rgba(0, 0, 0, 0.3)
    lineGenericActive: Qt.rgba(0, 0, 0, 0.3)
    lineGenericHover: Qt.rgba(0, 0, 0, 0.15)
    lineGenericSolid: "#E5E5E5"
    lineInfo: Qt.rgba(54 / 255, 151 / 255, 241 / 255, 0.8)
    lineLight: Qt.rgba(1, 1, 1, 0.5)
    lineMisc: Qt.rgba(107 / 255, 132 / 255, 153 / 255, 0.8)
    linePositive: Qt.rgba(50 / 255, 186 / 255, 118 / 255, 0.8)
    lineUtility: Qt.rgba(143 / 255, 82 / 255, 204 / 255, 0.8)
    lineWarning: "#E9AE56"

    scrollCorner: Qt.rgba(0, 0, 0, 0.1)
    scrollHandle: Qt.rgba(0, 0, 0, 0.1)
    scrollHandleHover: Qt.rgba(0, 0, 0, 0.15)
    scrollTrack: "#FFFFFF"

    sfxFade: Qt.rgba(1, 1, 1, 0.3)
    sfxShadow: Qt.rgba(0, 0, 0, 0.15)
    sfxShadowHeavy: Qt.rgba(0, 0, 0, 0.5)
    sfxShadowLight: Qt.rgba(0, 0, 0, 0.05)
    sfxVeil: Qt.rgba(0, 0, 0, 0.25)

    textBrand: "#BD8E4B"
    textBrandContrast: Qt.rgba(0, 0, 0, 0.85)
    textBrandHeavy: "#BD5C0A"
    textComplementary: Qt.rgba(0, 0, 0, 0.7)
    textDanger: "#E9033A"
    textDangerHeavy: "#BD0935"
    textDarkComplementary: Qt.rgba(0, 0, 0, 0.7)
    textDarkHint: Qt.rgba(0, 0, 0, 0.3)
    textDarkPrimary: Qt.rgba(0, 0, 0, 0.85)
    textDarkSecondary: Qt.rgba(0, 0, 0, 0.5)
    textHint: Qt.rgba(0, 0, 0, 0.3)
    textInfo: "#348BDC"
    textInfoHeavy: "#3072B3"
    textInvertedComplementary: Qt.rgba(1, 1, 1, 0.85)
    textInvertedHint: Qt.rgba(1, 1, 1, 0.5)
    textInvertedPrimary: "#FFFFFF"
    textInvertedSecondary: Qt.rgba(1, 1, 1, 0.7)
    textLightComplementary: Qt.rgba(1, 1, 1, 0.85)
    textLightHint: Qt.rgba(1, 1, 1, 0.5)
    textLightPrimary: "#FFFFFF"
    textLightSecondary: Qt.rgba(1, 1, 1, 0.7)
    textLink: "#D39E50"
    textLinkHover: "#D36507"
    textLinkVisited: "#8F52CC"
    textLinkVisitedHover: "#593877"
    textMisc: "#647A8D"
    textMiscHeavy: "#556575"
    textPositive: "#30AA6E"
    textPositiveHeavy: "#2D8B5D"
    textPrimary: Qt.rgba(0, 0, 0, 0.85)
    textSecondary: Qt.rgba(0, 0, 0, 0.5)
    textUtility: "#844DBB"
    textUtilityHeavy: "#6E4299"
    textWarning: "#BD8E4B"
    textWarningHeavy: "#BD5C0A"
}
