// GENERATED by tools/gen-tokens/gen_tokens.py from @gravity-ui/uikit 7.49.0. Do not edit by hand.

import QtQuick

// .g-root_theme_light-hc
ColorTokens {

    baseBackground: "#FFFFFF"
    baseBrand: "#FFBE5C"
    baseBrandHover: "#D09B4D"
    baseDangerHeavy: "#B80530"
    baseDangerHeavyHover: "#890928"
    baseDangerLight: Qt.rgba(1, 0, 61 / 255, 0.4)
    baseDangerLightHover: Qt.rgba(1, 0, 61 / 255, 0.6)
    baseDangerMedium: Qt.rgba(1, 0, 61 / 255, 0.7)
    baseDangerMediumHover: Qt.rgba(1, 0, 61 / 255, 0.9)
    baseFloat: "#FFFFFF"
    baseFloatAccent: "#FFFFFF"
    baseFloatAccentHover: Qt.rgba(1, 1, 1, 0.85)
    baseFloatAnnouncement: "#E1E6EB"
    baseFloatHeavy: "#4C4C4C"
    baseFloatHover: "#D9D9D9"
    baseFloatMedium: "#737373"
    baseGeneric: Qt.rgba(0, 0, 0, 0.15)
    baseGenericAccent: Qt.rgba(0, 0, 0, 0.25)
    baseGenericAccentDisabled: Qt.rgba(0, 0, 0, 0.15)
    baseGenericHover: Qt.rgba(0, 0, 0, 0.3)
    baseGenericMedium: Qt.rgba(0, 0, 0, 0.25)
    baseGenericMediumHover: Qt.rgba(0, 0, 0, 0.35)
    baseGenericUltralight: "#F2F2F2"
    baseInfoHeavy: "#2B6FAE"
    baseInfoHeavyHover: "#20476B"
    baseInfoLight: Qt.rgba(54 / 255, 151 / 255, 241 / 255, 0.4)
    baseInfoLightHover: Qt.rgba(54 / 255, 151 / 255, 241 / 255, 0.6)
    baseInfoMedium: Qt.rgba(54 / 255, 151 / 255, 241 / 255, 0.7)
    baseInfoMediumHover: Qt.rgba(54 / 255, 151 / 255, 241 / 255, 0.9)
    baseLight: "#FFFFFF"
    baseLightAccentDisabled: Qt.rgba(1, 1, 1, 0.3)
    baseLightDisabled: Qt.rgba(1, 1, 1, 0.15)
    baseLightHover: Qt.rgba(1, 1, 1, 0.85)
    baseLightSimpleHover: Qt.rgba(1, 1, 1, 0.3)
    baseMiscHeavy: "#506271"
    baseMiscHeavyHover: "#3F4B56"
    baseMiscLight: Qt.rgba(107 / 255, 132 / 255, 153 / 255, 0.4)
    baseMiscLightHover: Qt.rgba(107 / 255, 132 / 255, 153 / 255, 0.6)
    baseMiscMedium: Qt.rgba(107 / 255, 132 / 255, 153 / 255, 0.7)
    baseMiscMediumHover: Qt.rgba(107 / 255, 132 / 255, 153 / 255, 0.9)
    baseModal: "#FFFFFF"
    baseNeutralHeavy: Qt.rgba(0, 0, 0, 0.55)
    baseNeutralHeavyHover: Qt.rgba(0, 0, 0, 0.65)
    baseNeutralLight: Qt.rgba(0, 0, 0, 0.15)
    baseNeutralLightHover: Qt.rgba(0, 0, 0, 0.25)
    baseNeutralMedium: Qt.rgba(0, 0, 0, 0.3)
    baseNeutralMediumHover: Qt.rgba(0, 0, 0, 0.4)
    basePositiveHeavy: "#288758"
    basePositiveHeavyHover: "#226644"
    basePositiveLight: Qt.rgba(50 / 255, 186 / 255, 118 / 255, 0.4)
    basePositiveLightHover: Qt.rgba(50 / 255, 186 / 255, 118 / 255, 0.6)
    basePositiveMedium: Qt.rgba(50 / 255, 186 / 255, 118 / 255, 0.7)
    basePositiveMediumHover: Qt.rgba(50 / 255, 186 / 255, 118 / 255, 0.9)
    baseSelection: Qt.rgba(1, 190 / 255, 92 / 255, 0.5)
    baseSelectionHover: Qt.rgba(1, 190 / 255, 92 / 255, 0.7)
    baseSimpleHover: Qt.rgba(0, 0, 0, 0.15)
    baseSimpleHoverSolid: "#D9D9D9"
    baseUtilityHeavy: "#6A3F94"
    baseUtilityHeavyHover: "#51326F"
    baseUtilityLight: Qt.rgba(143 / 255, 82 / 255, 204 / 255, 0.4)
    baseUtilityLightHover: Qt.rgba(143 / 255, 82 / 255, 204 / 255, 0.6)
    baseUtilityMedium: Qt.rgba(143 / 255, 82 / 255, 204 / 255, 0.7)
    baseUtilityMediumHover: Qt.rgba(143 / 255, 82 / 255, 204 / 255, 0.9)
    baseWarningHeavy: "#E7AD55"
    baseWarningHeavyHover: "#B88A46"
    baseWarningLight: Qt.rgba(1, 190 / 255, 92 / 255, 0.5)
    baseWarningLightHover: Qt.rgba(1, 190 / 255, 92 / 255, 0.7)
    baseWarningMedium: Qt.rgba(1, 190 / 255, 92 / 255, 0.7)
    baseWarningMediumHover: "#FFBE5C"

    infographicsAxis: "#D9D9D9"
    infographicsTooltipBg: Qt.rgba(1, 1, 1, 0.95)

    lineBrand: "#E7AD55"
    lineDanger: Qt.rgba(1, 0, 61 / 255, 0.8)
    lineFocus: Qt.rgba(107 / 255, 132 / 255, 153 / 255, 0.8)
    lineGeneric: Qt.rgba(0, 0, 0, 0.2)
    lineGenericAccent: Qt.rgba(0, 0, 0, 0.3)
    lineGenericAccentHover: Qt.rgba(0, 0, 0, 0.7)
    lineGenericActive: Qt.rgba(0, 0, 0, 0.7)
    lineGenericHover: Qt.rgba(0, 0, 0, 0.4)
    lineGenericSolid: "#CCCCCC"
    lineInfo: Qt.rgba(54 / 255, 151 / 255, 241 / 255, 0.8)
    lineLight: Qt.rgba(1, 1, 1, 0.5)
    lineMisc: Qt.rgba(107 / 255, 132 / 255, 153 / 255, 0.8)
    linePositive: Qt.rgba(50 / 255, 186 / 255, 118 / 255, 0.8)
    lineUtility: Qt.rgba(143 / 255, 82 / 255, 204 / 255, 0.8)
    lineWarning: "#E7AD55"

    scrollCorner: Qt.rgba(0, 0, 0, 0.1)
    scrollHandle: Qt.rgba(0, 0, 0, 0.1)
    scrollHandleHover: Qt.rgba(0, 0, 0, 0.15)
    scrollTrack: "#FFFFFF"

    sfxFade: Qt.rgba(1, 1, 1, 0.3)
    sfxShadow: Qt.rgba(0, 0, 0, 0.3)
    sfxShadowHeavy: Qt.rgba(0, 0, 0, 0.6)
    sfxShadowLight: Qt.rgba(0, 0, 0, 0.1)
    sfxVeil: Qt.rgba(0, 0, 0, 0.45)

    textBrand: "#B88A46"
    textBrandContrast: "#000000"
    textBrandHeavy: "#59300D"
    textComplementary: Qt.rgba(0, 0, 0, 0.85)
    textDanger: "#D00334"
    textDangerHeavy: "#590C1F"
    textDarkComplementary: Qt.rgba(0, 0, 0, 0.85)
    textDarkHint: Qt.rgba(0, 0, 0, 0.5)
    textDarkPrimary: "#000000"
    textDarkSecondary: Qt.rgba(0, 0, 0, 0.7)
    textHint: Qt.rgba(0, 0, 0, 0.5)
    textInfo: "#2F7CC4"
    textInfoHeavy: "#1D3955"
    textInvertedComplementary: Qt.rgba(1, 1, 1, 0.85)
    textInvertedHint: Qt.rgba(1, 1, 1, 0.5)
    textInvertedPrimary: "#FFFFFF"
    textInvertedSecondary: Qt.rgba(1, 1, 1, 0.7)
    textLightComplementary: Qt.rgba(1, 1, 1, 0.85)
    textLightHint: Qt.rgba(1, 1, 1, 0.5)
    textLightPrimary: "#FFFFFF"
    textLightSecondary: Qt.rgba(1, 1, 1, 0.7)
    textLink: "#B88A46"
    textLinkHover: "#B85805"
    textLinkVisited: "#834CB9"
    textLinkVisitedHover: "#442B5C"
    textMisc: "#596D7E"
    textMiscHeavy: "#2D343B"
    textPositive: "#2C9862"
    textPositiveHeavy: "#1C4430"
    textPrimary: "#000000"
    textSecondary: Qt.rgba(0, 0, 0, 0.7)
    textUtility: "#7645A7"
    textUtilityHeavy: "#38254A"
    textWarning: "#B88A46"
    textWarningHeavy: "#59300D"
}
